name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - dev
      - main  # Assuming this corresponds to the master branch
  pull_request:
    branches:
      - dev
      - main
  schedule:
    - cron: "0 0 * * *"

env:
  REGISTRY: docker.io
  IMAGE_NAME: alexslx/srtla-relay-server

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Update latest tag (for main branch)
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ "$BRANCH_NAME" == "main" ]]; then
            # Execute commands for main branch
            echo "Updating latest tag on Docker Hub"
            docker pull "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$BRANCH_NAME"
            docker tag "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$BRANCH_NAME" "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
            docker push "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          else
            echo "Skipped."
          fi
